name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

 
      - name: docker login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      
      - name: Build and push
        uses: docker/build-push-action@v5.2.0
        with:   
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/alphaminiecomercebackend

      - name: Build and push
        uses: docker/build-push-action@v5.2.0
        with:   
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/alphaminiecomercefrontend

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true
         
      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1
          sed -i "s/GCP_PROJECT_ID/$GCP_PROJECT_ID/g" deployment.yaml
          kubectl apply -f deployment.yml
      
