name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

 
      - name: docker login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      
      - name: Build and push
        uses: docker/build-push-action@v5.2.0
        with:   
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/alphaminiecomercebackend

      - name: Build and push
        uses: docker/build-push-action@v5.2.0
        with:   
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/alphaminiecomercefrontend

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true
         

      - name: Deploy
        run: |
          ./kustomize edit set image gcr.io/${{GCP_PROJECT_ID}}/IMAGE:TAG=gcr.io/${{GCP_PROJECT_ID}}/${{ secrets.DOCKERHUB_USER }}/alphaminiecomercebackend
          ./kustomize edit set image gcr.io/${{GCP_PROJECT_ID}}/IMAGE:TAG=gcr.io/${{GCP_PROJECT_ID}}/ ${{ secrets.DOCKERHUB_USER }}/alphaminiecomercefrontend
          ./kustomize build . | kubectl apply -f deployment.yml
          kubectl get services -o wide
        
